# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZKpnl2pV4m5M09QMYtROcpg7EhJTjnrb
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

# =========================
# SETUP
# =========================
base_url = "https://books.toscrape.com/"
data = []

page = 1
max_rows = 250  # change to 200 or 300 if you want

# =========================
# SCRAPING LOOP
# =========================
while len(data) < max_rows:
    url = f"https://books.toscrape.com/catalogue/page-{page}.html"
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")

    books = soup.find_all("article", class_="product_pod")

    # stop if no data found
    if not books:
        break

    for book in books:
        if len(data) >= max_rows:
            break

        # -----------------
        # TITLE
        # -----------------
        title = book.h3.a["title"]

        # -----------------
        # PRICE (clean numeric)
        # -----------------
        price_text = book.find("p", class_="price_color").text
        price = float(price_text.replace("£", "").replace("Â", "").strip()) # Fixed: Added .replace("Â", "")

        # -----------------
        # AVAILABILITY
        # -----------------
        availability = book.find("p", class_="instock availability").text.strip()

        # -----------------
        # RATING (convert to number)
        # -----------------
        rating_class = book.find("p")["class"]
        rating_text = rating_class[1]

        rating_map = {
            "One": 1,
            "Two": 2,
            "Three": 3,
            "Four": 4,
            "Five": 5
        }

        rating = rating_map.get(rating_text, 0)

        # -----------------
        # PRODUCT LINK
        # -----------------
        relative_link = book.h3.a["href"]
        product_link = base_url + "catalogue/" + relative_link

        # -----------------
        # SAVE DATA
        # -----------------
        data.append({
            "Title": title,
            "Price (£)": price,
            "Availability": availability,
            "Rating": rating,
            "Product Link": product_link
        })

    page += 1
    time.sleep(1)  # polite scraping

# =========================
# CREATE DATAFRAME
# =========================
df = pd.DataFrame(data)

# =========================
# SAVE FILE
# =========================
file_name = "books_dataset.csv"
df.to_csv(file_name, index=False)

# =========================
# OUTPUT
# =========================
print("✅ Scraping Complete!")
print("Total Rows:", len(df))
df.head()

from google.colab import files
files.download("books_dataset.csv")