# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZKpnl2pV4m5M09QMYtROcpg7EhJTjnrb
"""

!pip install requests beautifulsoup4 pandas
import requests
from bs4 import BeautifulSoup
import pandas as pd

base_url = "https://books.toscrape.com/"
data = []

page = 1

while len(data) < 250:  # 👈 limit rows here
    url = f"https://books.toscrape.com/catalogue/page-{page}.html"
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")

    books = soup.find_all("article", class_="product_pod")

    if not books:
        break  # stop if no more pages

    for book in books:
        if len(data) >= 250:
            break  # stop exactly at 250

        # Title
        title = book.h3.a["title"]

        # Price
        price_text = book.find("p", class_="price_color").text
        price = float(price_text.replace("£", "").replace("Â", "")) # Added .replace("Â", "") to fix encoding issue

        # Availability
        availability = book.find("p", class_="instock availability").text.strip()

        # Rating
        rating_class = book.find("p")["class"]
        rating_text = rating_class[1]

        rating_map = {
            "One": 1, "Two": 2, "Three": 3,
            "Four": 4, "Five": 5
        }
        rating = rating_map.get(rating_text, 0)

        # Product Link
        relative_link = book.h3.a["href"]
        product_link = base_url + "catalogue/" + relative_link

        data.append({
            "Title": title,
            "Price (£)": price,
            "Availability": availability,
            "Rating": rating,
            "Product Link": product_link
        })

    page += 1

df = pd.DataFrame(data)
df.to_csv("books_250_rows.csv", index=False)

print("Total rows scraped:", len(df))
print(df.head())